case_management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users import views as user_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/<str:usertype>/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('confirm-login/', user_views.confirm_login, name='confirm-login'),
    path('user/', include('users.urls')),
    path('team/', include('teams.urls')),
    path('project/', include('projects.urls')),
    path('', user_views.start, name='start'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path
from .views import (
    # TeamListView,
    TeamNewUserView,
    TeamDetailView,
    TeamAddUser,
    TeamUserUpdate,
    TeamCreateView,
    TeamUpdateView,
    TeamProjectListView,
    TeamProjectRequestListView
)

urlpatterns = [
    # path('<int:pk>/<str:slug>/', TeamListView.as_view(), name='team-index'),
    path('new-user/', TeamNewUserView.as_view(), name='team-new-user'),
    path('<int:pk>/<str:slug>/', TeamDetailView.as_view(), name='team-detail'),
    path('<int:pk>/<str:slug>/users/add/', TeamAddUser.as_view(), name='team-add-user'),
    path('<int:tpk>/<str:slug>/users/<int:pk>/update/', TeamUserUpdate.as_view(), name='team-user-update'),
    path('<int:pk>/<str:slug>/update/', TeamUpdateView.as_view(), name='team-update'),
    path('create/', TeamCreateView.as_view(), name='team-create'),
    path('<int:pk>/<str:slug>/projects/', TeamProjectListView.as_view(), name='team-projects'),
    path('<int:pk>/<str:slug>/projects/requests/', TeamProjectRequestListView.as_view(), name='team-project-requests'),
]

projects/models.py
from django.db import models

from django.shortcuts import reverse
from django.utils.text import slugify
from django.utils import timezone

from django.contrib.auth.models import User

from blobstorage import AzureStorage

import os

# Create your models here.
class Project(models.Model):

    class Status(models.TextChoices):
        PENDING = ('PENDING', 'Modtaget')
        CURRENT = ('CURRENT', 'Igangværende')
        DONE = ('DONE', 'Færdig')

    team = models.ForeignKey(
        'teams.Team',
        on_delete=models.SET_DEFAULT,
        # blank=True,
        # null=True,
        default=None,
        help_text='Holdet i firmaet, som du ønsker skal tage imod dit projekt.'# <br>Hvis du ikke vælger et, kan ethvert hold tage imod det.'
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.SET_DEFAULT,
        default=None,
        related_name='owner'
    )
    leader = models.ForeignKey(
        User,
        on_delete=models.SET_DEFAULT,
        related_name='leader',
        blank=True,
        null=True,
        default=None
    )
    users = models.ManyToManyField("users.profile", blank=True)

    name = models.CharField(
        max_length=255,
        help_text='Navnet på dit projekt.',
        error_messages={"required":"Navnefeltet er påkrævet."}    
    )
    description = models.TextField(
        help_text='En klar og detaljeret beskrivelse af projektet.',
        error_messages={"required":"Beskrivelsesfeltet er påkrævet"}
    )
    slug = models.SlugField(max_length=255, blank=True)

    status = models.CharField(
        max_length = 255,
        choices=Status.choices,
        default=Status.PENDING
    )

    # Field starts out as NULL, but gets set automagically post-save (check signals.py)
    azure_container = models.CharField(
        max_length=255,
        blank=True,
        default=None,
        null=True
    )

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def worker_count(self):
        # if self.leader is None:
        #     return self.users.all().count()
        return self.users.all().exclude(user=self.leader).count()

    def save(self, *args, **kwargs):
        # Create slug
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.pk, "slug": self.slug})
    
    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(
        max_length=255,
        error_messages={"required":"Titel feltet er påkrævet."}
    )
    description = models.CharField(
        max_length=255,
        error_messages={"required":"Beskrivelsesfeltet er påkrævet."}
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.project.pk, "slug": self.project.slug})

    def __str__(self):
        return self.title


# def get_upload_path(instance, filename):
#     return os.path.join('img', str(instance.project.pk), filename)

class Media(models.Model):
    title = models.CharField(
        max_length=255,
        error_messages={"required":"Titel feltet er påkrævet."}
    )
    description = models.CharField(
        max_length=255,
        error_messages={"required":"Beskrivelsesfeltet er påkrævet."}
    )

    # img = models.ImageField(upload_to=None, null=True, default=None)
    blob = models.CharField(max_length=255, blank=True)
    blob_url = models.CharField(max_length=255, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.project.pk, "slug": self.project.slug})


    def __str__(self):
        return self.title

teams/models.py
from django.db import models

from django.shortcuts import reverse

from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class Team(models.Model):
    name = models.CharField(
        max_length = 255,
        unique=True,
        help_text="Et beskrivende navn til dit hold. Dette er navnet kunder og kollegaer vil se, når de vil oprette et projekt til dig.",
        error_messages={"required": "Navnefeltet er påkrævet."}
    )
    description = models.CharField(
        max_length = 255,
        help_text="En lille beskrivelse af dit holds funktion.",
        error_messages={"required": "Beskrivelsesfeltet er påkrævet."}
    )
    slug = models.SlugField(
        max_length=255,
        blank=True,
        help_text='Dette felt vil automatisk blive udfyldt når du opretter holdet.'
    )

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("team-detail", kwargs={"pk": self.pk, "slug": self.slug})

    def __str__(self):
        return self.name


# Manager to return custom querysets from a table
class NotificationManager(models.Manager):
    def get_unread(self):
        return self.filter(read_at=None)        

class Notification(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    project = models.OneToOneField("projects.Project", on_delete=models.CASCADE)

    read_at = models.DateTimeField(blank=True, null=True, default=None)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    # Set model's manager to the custom manager
    objects = NotificationManager()

    def __str__(self):
        return f'({self.project.name}, {self.team.name})'

teams/forms.py
from django import forms
from users.models import Profile, Role
from django.db.models import Q


# Custom class inheriting from ModelChoiceField, in order to change the text shown in a Select field's options.
class TeamUserRoleChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.display_name


# Custom form to limit the amount of options in the Select field
class UpdateTeamUserRoleForm(forms.ModelForm):
    role = forms.ModelChoiceField(
        queryset=Role.objects.filter(Q(name='Team Leader') | Q(name='Team Member')),
        label='Roller'
    )
    # roles = TeamUserRoleChoiceField(
    #     queryset=Role.objects.filter(Q(name='Team Leader') | Q(name='Team Member')),
    #     label='Roller'
    # )

    class Meta:
        model = Profile
        fields = ('role',)

teams/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import Http404
from django.contrib import messages

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    TemplateView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Team
from .forms import UpdateTeamUserRoleForm
from users.models import Profile, Role
from django.contrib.auth.models import User
from projects.models import Project

from role_permissions.rules import (
    TeamLeaderRequiredMixin,
    TeamNewUserRequiredMixin,
    TeamUserAnyRequiredMixin
)


class TeamNewUserView(LoginRequiredMixin, TeamNewUserRequiredMixin, TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'teams/team_new_user.html')


class TeamCreateView(LoginRequiredMixin, TeamLeaderRequiredMixin, CreateView):
    model = Team
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['legend'] = 'Opret nyt hold'
        ctx['btn'] = 'Opret'
        return ctx
    
    def form_valid(self, form):
        if self.request.user.profile.team is None:
            # Save the form instance
            super().form_valid(form)
            # Set user's team to be the one they just created
            self.request.user.profile.team = form.instance
            self.request.user.profile.role = Role.objects.get(name='Team Leader')
            self.request.user.profile.save()
            # Redirect
            return redirect(reverse('team-detail', kwargs={"pk": form.instance.pk, "slug": form.instance.slug}))
        else:
            return super().form_valid(form)


class TeamUpdateView(LoginRequiredMixin, TeamLeaderRequiredMixin, UpdateView):
    model = Team
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['legend'] = 'Opdater hold'
        ctx['btn'] = 'Gem'
        return ctx
    
    def get_object(self, queryset=None):
        team = super().get_object()
        if team != self.request.user.profile.team:
            raise Http404
        return team


class TeamDetailView(LoginRequiredMixin, TeamUserAnyRequiredMixin, DetailView):
    model = Team

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        team = get_object_or_404(Team, pk=self.kwargs['pk'], slug=self.kwargs['slug'])
        
        ctx['team'] = team
        ctx['team_leaders'] = User.objects.filter(profile__team=team, profile__role__name='Team Leader').count()
        ctx['team_members'] = User.objects.filter(profile__team=team, profile__role__name='Team Member').count()
        ctx['team_users'] = User.objects.filter(profile__team=team)

        ctx['projects'] = Project.objects.filter(team=team).exclude(leader=None)
        ctx['active_projects'] = Project.objects.filter(team=team, status=Project.Status.CURRENT)
        ctx['finished_projects'] = Project.objects.filter(team=team, status=Project.Status.DONE)
        ctx['no_projects_msg'] = 'Dit hold har endnu ikke modtaget nogen projekter.'
        # ctx['projects'] = Project.objects.filter(team=team).order_by('-created_at')
        # ctx['active_projects'] = [project for project in ctx['projects'] if project.status is Project.Status.CURRENT]
        # ctx['finished_projects'] = [project for project in ctx['projects'] if project.status is Project.Status.DONE]
        return ctx


class TeamAddUser(LoginRequiredMixin, TeamLeaderRequiredMixin, TemplateView):
    def get(self, request, **kwargs):
        teamless_role = Role.objects.get(name='Team')
        team_users = User.objects.filter(profile__team=None, profile__role=teamless_role)
        ctx = {
            "team_users": team_users
        }
        return render(request, 'teams/team_add_user.html', context=ctx)


    def post(self, request, **kwargs):
        user_pk = request.POST['user_pk']
        user = get_object_or_404(User, pk=user_pk)
        if user.profile.team == None:
            team = Team.objects.get(pk=kwargs.get('pk'), slug=kwargs.get('slug'))
            role = Role.objects.get(name='Team Member')
            user.profile.team = team
            user.profile.role = role
            user.profile.save()
            messages.success(request, f'{user.username} er nu tilføjet til {team.name} som elev!')
        else:
            messages.danger(request, f'{user.username} er allerede på et hold, og kan derfor ikke tilføjes.')
        return redirect(reverse('team-add-user', kwargs=kwargs))


class TeamUserUpdate(LoginRequiredMixin, TeamLeaderRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateTeamUserRoleForm
    template_name = 'teams/team_user_form.html'
    
    def get_object(self, queryset=None):
        return Profile.objects.get(user__pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('team-detail', kwargs={
            "pk": self.kwargs.get('tpk'),
            "slug": self.kwargs.get('slug')
        })


class TeamProjectListView(LoginRequiredMixin, TeamUserAnyRequiredMixin, ListView):
    model = Project
    template_name = 'teams/team_project_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        projects = Project.objects.filter(
            team__pk=self.kwargs['pk'],
            team__slug=self.kwargs['slug'],
            status__in=[
                Project.Status.CURRENT,
                Project.Status.DONE
            ]
        ).exclude(leader=None).order_by('-created_at')
        ctx['active_projects'] = []
        ctx['finished_projects'] = []
        ctx['no_projects_msg'] = 'Der er ingen projekter under denne kategori.'

        for project in projects:
            # Ignore PENDING projects
            if project.status == Project.Status.CURRENT:
                ctx['active_projects'].append(project)
            if project.status == Project.Status.DONE:
                ctx['finished_projects'].append(project)
        return ctx


class TeamProjectRequestListView(LoginRequiredMixin, TeamLeaderRequiredMixin, ListView):
    model = Project
    template_name = 'teams/team_project_request_list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['no_projects_msg'] = 'Der er ingen nye projekter at finde.'
        return ctx

    def get_queryset(self):
        projects = Project.objects.filter(team__pk=self.kwargs['pk'], leader=None)
        return projects


# THIS VIEW IS NOT IN USE. THE REASON BEING IT ONLY DISPLAYS DATA WHICH IS ALSO AVAILABLE IN THE TeamDetailView VIEW
# class TeamListView(LoginRequiredMixin, TeamLeaderRequiredMixin, ListView):
#     model = Profile
#     template_name = 'teams/index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['team'] = get_object_or_404(Team, pk=self.kwargs['pk'], slug=self.kwargs['slug'])
#         context['team_users'] = User.objects.filter(profile__team=context['team'])
#         return context

#     # def get_queryset(self):
#     #     return Profile.objects.filter(team=self.request.user.profile.team)

teams/templates/teams/index.html
{% comment %}  {% endcomment %}
    {% comment %} THERE ARE CURRENTLY NO ROUTES THAT LEAD TO THIS PAGE, AS IT IS NOT BEING USED. {% endcomment %}
{% comment %}  {% endcomment %}


{% comment %} {% extends 'base.html' %}
{% block content-fluid %}
<div class="content-section">
    <h1>Hold oversigt</h1>
    <p>
        Dette er en oversigt over medarbejdere, som er indmeldt på dit hold. Det er ikke muligt at få en oversigt over andre hold end dit eget.<br>
        Klik på en medarbejders navn for at se deres profil.
    </p>
</div>
<div class="content-section">
    <div class="row">
        <div class="col">
            <h2>{{ team.name }}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th>Medarbejder</th>
                        <th>Brugernavn</th>
                        <th>Antal projekter</th>
                        <th>Oprettet</th>
                    </tr>
                </thead>
                {% for member in team_users %}
                    <tr>
                        <td><a href="#">{{ member.get_full_name }}</a></td>
                        <td>{{ member.username }}</td>
                        <td>NYI</td>
                        <td>{{ member.created_at|date:"d M, Y" }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content-fluid %} {% endcomment %}

teams/templates/teams/team_add_user.html
{% extends 'base.html' %}

{% block content-fluid %}
<div class="row">
    <div class="col offset-md-1 mb-2">
        <h1>Tilføj medarbejdere - {{ user.profile.team.name }}</h1>
        <h4>Her kan du tilføje brugere til dit hold. Efter tilføjelse, kan du sætte dem til at arbejde på projekter.</h4>
    </div>
</div>
<div class="row">
    <div class="col offset-md-1 mb-2">
        <a href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Gå tilbage</a>
    </div>
</div>

<div class="row">
    <div class="col-md-10 offset-md-1 content-section">
        <h3>Bruger oversigt</h3>
        <div>En liste af alle brugere, som endnu ikke er medlem af noget hold.</div>
        <div class="row mt-2">
            <div class="col">
                {% if team_users|length > 0 %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Navn</th>
                            <th>Brugernavn</th>
                            <th>Rolle</th>
                            <th>Projekter</th>
                            <th>Oprettet</th>
                            <th>Handlinger</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tu in team_users %}
                            <tr>
                                <td>{{ tu.get_full_name }}</td>
                                <td>{{ tu.username }}</td>
                                <td>{{ tu.profile.role.display_name }}</td>
                                <td>{{ tu.project_set.all|length }}</td>
                                <td>{{ tu.profile.created_at|date:"d M, Y" }}</td>
                                <td>
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            <input type="hidden" name="user_pk" value="{{ tu.pk }}">
                                        </fieldset>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Tilføj</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <hr>
                    <i><b>Der blev ikke fundet nogen nye brugere i systemet.</b></i>
                {% endif %}
            </div>
        </div>
    </div>    
</div>
<div class="row text-center">
    <div class="col mt-2">
        <a href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Gå tilbage</a>
    </div>
</div>

{% endblock content-fluid %}

teams/templates/teams/team_detail.html
{% extends 'base.html' %}

{% block content-fluid %}
{% comment %} Short overview {% endcomment %}
<div class="row">
    <div class="col offset-md-1 mb-2">
        <h1>Hold Detaljer - {{ team.name }}</h1>
        {% comment %} <div class="mt-2">
            <a href="{% url 'team-index' team.pk team.slug %}" class="btn btn-primary">Tilbage til oversigt</a>
        </div> {% endcomment %}
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-xs-12 offset-md-1">
        <div class="col content-section">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <h4>
                        Info om {{ team.name }} 
                        {% if user.profile.role.name == 'Team Leader' %}
                            - <a href="{% url 'team-update' team.pk team.slug %}" class="btn btn-sm btn-primary">Redigér hold</a>
                        {% endif %}
                    </h4>
                    <hr>
                </div>
                <div class="col-md-12">
                    <p><b>Oprettet:</b> {{ team.created_at|date:"d M, Y" }}</p>
                </div>
                <div class="col-md-6">
                    <p><b>Antal elever:</b> {{ team_members }}</p>
                </div>
                <div class="col-md-6">
                    <p><b>Antal instruktørere:</b> {{ team_leaders }}</p>
                </div>
                <div class="col-md-6">
                    <p><b>Aktive projekter:</b> {{ active_projects|length }}</p>
                </div>
                <div class="col-md-6">
                    <p><b>Færdiggjorte projekter:</b> {{ finished_projects|length }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="col content-section">
            <div class="row">
                <div class="col-md-12">
                    <h4>Hold beskrivelse</h4>
                    <hr>
                </div>
                <div class="col">
                    {{ team.description }}
                </div>
            </div>
        </div>
    </div>
</div>

{% comment %} Users table {% endcomment %}
<div class="row mt-3">
    <div class="col-md-10 offset-md-1 content-section">
        <h3>
            Bruger oversigt
            {% if user.profile.role.name == 'Team Leader' %}
                - <a href="{% url 'team-add-user' team.pk team.slug %}" class="btn btn-sm btn-primary">Tilføj bruger</a>
            {% endif %}
        </h3> 
        {% if team_users|length > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Navn</th>
                        <th>Brugernavn</th>
                        <th>Rolle</th>
                        <th>Projekter</th>
                        <th>Oprettet</th>
                        <th>Handlinger</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tu in team_users %}
                        <tr>
                            <td>{{ tu.get_full_name }}</td>
                            <td>{{ tu.username }}</td>
                            <td>{{ tu.profile.role.display_name }}</td>
                            <td>{{ tu.project_set.all|length }}</td>
                            <td>{{ tu.profile.created_at|date:"d M, Y" }}</td>
                            <td>
                                {% if user.profile.role.name == "Team Leader" %}
                                    <a href="{% url 'team-user-update' team.pk team.slug tu.pk %}" class="btn btn-sm btn-secondary">Ændr rolle</a>
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <i><b>Der er ingen brugere tilmeldt på holdet.</b></i>
        {% endif %}
    </div>
</div>

{% comment %} Projects table {% endcomment %}
<div class="row mt-3">
    <div class="col-md-10 col-xs-12 offset-md-1 content-section">
        <h3>Projekt Oversigt</h3>
        {% include 'projects/includes/project_table.html' %}
    </div>
</div>

{% endblock content-fluid %}

teams/templates/teams/team_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>Opret nyt hold</h2>
        <div>
            Oprettelse af nye hold er forbeholdt instruktører.<br>
            Hvis du <b>ikke</b> er instruktør på skolepraktikken, bedes du undlade at oprette et nyt hold.
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend>{{ legend }}</legend>
                <hr>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">{{ btn }}</button>
            </div>
        </form>
        {% if user.profile.team %}
            <div class="center-text">
                <small>Fortrudt? <a href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Gå tilbage</a></small>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

teams/templates/teams/team_new_user.html
{% extends 'base.html' %}

{% block content-fluid %}
<div class="row">
    <div class="col-md-10 offset-md-1">
        <h2>Velkommen til sagsstyringssystemet hos SKP!</h2>
        <h4>Da du lige har oprettet din bruger, er du ikke tilmeldt et hold. Du skal være tilmeldt et hold, før du kan begynde at arbejde på projekter.</h4>
    </div>
    <div class="row mt-2">
        <div class="col-md-4 offset-md-1">
            <div class="col content-section">
                <h3>Er du elev?</h3>
                <hr>
                <div>
                    <h5>Hvis du er elev, skal du blot informere din instruktør om, at du har oprettet din bruger. Du vil herefter tilmelde dig på deres hold, og så skal du bare genindlæse siden for at opdatere.</h5>
                </div>
            </div>
        </div>
        <div class="col-md-4 offset-md-1">
            <div class="col content-section">
                <h3>Er du instruktør?</h3>
                <hr>
                <div>
                    <h5>Hvis du er instruktør, kan du få en af dine medarbejdere til at tilmelde dig deres hold.</h5>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content-fluid %}

teams/templates/teams/team_project_list.html
{% extends 'base.html' %}
{% block content-fluid %}

{% comment %} Short description of the page {% endcomment %}
<div class="col-md-10 offset-md-1 mb-4 content-section">
    <h1>Projekt oversigt</h1>
    <div>
        Dette er en oversigt over alle projekter, dit hold har modtaget.<br>
        Klik på et projekts navn for at se deres flere detajler om det, samt udføre handlinger derpå.
    </div>
</div>

{% comment %} Active projects {% endcomment %}
<div class="row">
    <div class="col-md-10 offset-md-1 content-section">
        <h2>Igangværende projekter</h2>
        {% include 'projects/includes/project_table.html' with projects=active_projects %}
    </div>
</div>

{% comment %} Completed projects {% endcomment %}
<div class="row">
    <div class="col-md-10 offset-md-1 content-section">
        <h2>Færdiggjorte projekter</h2>
        {% include 'projects/includes/project_table.html' with projects=finished_projects %}
    </div>
</div>
{% endblock content-fluid %}

teams/templates/teams/team_project_request_list.html
{% extends 'base.html' %}
{% block content-fluid %}

{% comment %} Short description of the page {% endcomment %}
<div class="col-md-10 offset-md-1 mb-4 content-section">
    <h1>Kunde anmodninger</h1>
    <div>
        Dette er en oversigt over alle projekter, dit hold har modtaget, men ingen arbejder på.<br>
        Herfra kan du tage imod projektet, og derefter sætte dine elever på det!
    </div>
</div>

{% comment %} Active projects {% endcomment %}
<div class="row">
    <div class="col-md-10 offset-md-1 content-section">
        <h2>Projekter</h2>
        {% include 'projects/includes/project_table.html' with projects=object_list %}
    </div>
</div>
{% endblock content-fluid %}

teams/templates/teams/team_user_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>Rediger bruger rolle</h2>
    </div>
</div>
<div class="row mt-3">
    <div class="col content-section">
        <h4>Du er ved at ændre på <b>{{ object.user.username }}s</b> rolle.</h4>
        <div>En rolle bestemmer hvilke rettigheder en bruger har på systemet. Instruktørere kan langt mere end elever kan.</div>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Gem">
                {% comment %} <button type="submit" class="btn btn-primary">Gem</button> {% endcomment %}
            </div>
        </form>
        {% if user.profile.team %}
            <div class="center-text">
                <small>Fortrudt? <a href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Gå tilbage</a></small>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}