case_management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users import views as user_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/<str:usertype>/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('confirm-login/', user_views.confirm_login, name='confirm-login'),
    path('user/', include('users.urls')),
    path('team/', include('teams.urls')),
    path('project/', include('projects.urls')),
    path('', user_views.start, name='start'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path
from .views import (
    # TeamListView,
    TeamNewUserView,
    TeamDetailView,
    TeamAddUser,
    TeamUserUpdate,
    TeamCreateView,
    TeamUpdateView,
    TeamProjectListView,
    TeamProjectRequestListView
)

urlpatterns = [
    # path('<int:pk>/<str:slug>/', TeamListView.as_view(), name='team-index'),
    path('new-user/', TeamNewUserView.as_view(), name='team-new-user'),
    path('<int:pk>/<str:slug>/', TeamDetailView.as_view(), name='team-detail'),
    path('<int:pk>/<str:slug>/users/add/', TeamAddUser.as_view(), name='team-add-user'),
    path('<int:tpk>/<str:slug>/users/<int:pk>/update/', TeamUserUpdate.as_view(), name='team-user-update'),
    path('<int:pk>/<str:slug>/update/', TeamUpdateView.as_view(), name='team-update'),
    path('create/', TeamCreateView.as_view(), name='team-create'),
    path('<int:pk>/<str:slug>/projects/', TeamProjectListView.as_view(), name='team-projects'),
    path('<int:pk>/<str:slug>/projects/requests/', TeamProjectRequestListView.as_view(), name='team-project-requests'),
]

teams/models.py
from django.db import models

from django.shortcuts import reverse

from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class Team(models.Model):
    name = models.CharField(
        max_length = 255,
        unique=True,
        help_text="Et beskrivende navn til dit hold. Dette er navnet kunder og kollegaer vil se, når de vil oprette et projekt til dig.",
        error_messages={"required": "Navnefeltet er påkrævet."}
    )
    description = models.CharField(
        max_length = 255,
        help_text="En lille beskrivelse af dit holds funktion.",
        error_messages={"required": "Beskrivelsesfeltet er påkrævet."}
    )
    slug = models.SlugField(
        max_length=255,
        blank=True,
        help_text='Dette felt vil automatisk blive udfyldt når du opretter holdet.'
    )

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("team-detail", kwargs={"pk": self.pk, "slug": self.slug})

    def __str__(self):
        return self.name


# Manager to return custom querysets from a table
class NotificationManager(models.Manager):
    def get_unread(self):
        return self.filter(read_at=None)        

class Notification(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    project = models.OneToOneField("projects.Project", on_delete=models.CASCADE)

    read_at = models.DateTimeField(blank=True, null=True, default=None)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    # Set model's manager to the custom manager
    objects = NotificationManager()

    def __str__(self):
        return f'({self.project.name}, {self.team.name})'

case_management/templates/c_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Klient</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% comment %} Projects dropdown {% endcomment %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Projekter
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'client-projects' %}">Oversigt</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'project-create' %}">Opret nyt</a>
                </div>
            </li>
            {% comment %} /Projects dropdown {% endcomment %}

            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% include 'nav_components/user_section.html' %}
        </ul>
    </div>
</nav>

case_management/templates/main_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Main</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            
            {% comment %} Teams dropdown {% endcomment %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hold
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'team-index' user.profile.team.pk user.profile.team.slug %}">Oversigt</a>
                    <a class="dropdown-item" href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Detaljer</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Opret nyt</a>
                </div>
            </li>
            {% comment %} /Teams dropdown {% endcomment %}

            {% comment %} Projects dropdown {% endcomment %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Projekter
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'team-projects' user.profile.team.pk user.profile.team.slug %}">Oversigt</a>
                    <a class="dropdown-item" href="#">Kunde anmodninger</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'project-create' %}">Opret nyt</a>
                </div>
            </li>
            {% comment %} /Projects dropdown {% endcomment %}

            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log ud</a>
            </li>
        </ul>
    </div>
</nav>

case_management/templates/start_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'start' %}">Start</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log ind</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Opret
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'register' 'user' %}">Som medarbejder</a>
                    <a class="dropdown-item" href="{% url 'register' 'client' %}">Som kunde</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

case_management/templates/tl_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Leder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            
            {% comment %} Teams dropdown {% endcomment %}
            {% if user.profile.team %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hold
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% comment %} <a class="dropdown-item" href="{% url 'team-index' user.profile.team.pk user.profile.team.slug %}">Oversigt</a> {% endcomment %}
                        <a class="dropdown-item" href="{% url 'team-detail' user.profile.team.pk user.profile.team.slug %}">Detaljer</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'team-create' %}">Opret nyt</a>
                    </div>
                </li>
            {% comment %} /Teams dropdown {% endcomment %}

            {% comment %} Projects dropdown {% endcomment %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Projekter
                        {% if user.profile.team.notification_set.get_unread|length > 0 %}
                            <span class="badge badge-danger">{{ user.profile.team.notification_set.get_unread|length }}</span>
                        {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'team-projects' user.profile.team.pk user.profile.team.slug %}">
                            Oversigt
                        </a>
                        <a class="dropdown-item" href="{% url 'team-project-requests' user.profile.team.pk user.profile.team.slug %}">
                            Kunde anmodninger
                            {% if user.profile.team.notification_set.get_unread|length > 0 %}
                                <span class="badge badge-danger">{{ user.profile.team.notification_set.get_unread|length }}</span>
                            {% endif %}
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'project-create' %}">Opret nyt</a>
                    </div>
                </li>
            {% endif %}
            {% comment %} /Projects dropdown {% endcomment %}

            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% include 'nav_components/user_section.html' %}
        </ul>
    </div>
</nav>